name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - adwaita-icon-theme=48.0=unix_0
  - anaconda-anon-usage=0.7.0=py311hd6b623d_101
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.9.0=pyh29332c3_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - archspec=0.2.3=pyhd3eb1b0_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py311h460d6c5_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - atk-1.0=2.38.0=hd03087b_2
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - boltons=24.0.0=pyhd8ed1ab_1
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py311h3f08180_2
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - conda=25.7.0=py311h267d04e_0
  - conda-anaconda-telemetry=0.1.2=py311hca03da5_1
  - conda-anaconda-tos=0.1.3=py311hca03da5_0
  - conda-content-trust=0.2.0=pyhd8ed1ab_0
  - conda-libmamba-solver=25.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=pyh7900ff3_2
  - conda-package-streaming=0.11.0=pyhd8ed1ab_1
  - contourpy=1.3.2=py311h210dab8_0
  - cpp-expected=1.1.0=h48ca7d4_0
  - cpython=3.11.12=py311hd8ed1ab_0
  - cryptography=44.0.2=py311h8be0713_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.1.0=py311h9408147_1
  - dask-core=2025.10.0=pyhcf101f3_0
  - debugpy=1.8.14=py311h155a34a_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - dtumathtools=2024.2.0=pyhc5a7d3c_0
  - epoxy=1.5.10=h1c322ee_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - fmt=11.0.2=h440487c_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py311h4921393_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h1d14073_0
  - fribidi=1.0.10=h27ca646_0
  - frozendict=2.4.6=py311hae2e1ce_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - glib-tools=2.84.0=h1dc7a0c_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py311hb5d9ff4_3
  - graphite2=1.3.13=hebf3989_1003
  - graphviz=12.2.1=hff64154_1
  - gtk3=3.24.43=h07173f4_5
  - gts=0.7.6=he42f4ea_4
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.1.0=hab40de2_0
  - hicolor-icon-theme=0.17=hce30654_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs-lite=2019.12.3=py311h5d790af_8
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.1.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.6=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.14=pyhd8ed1ab_0
  - kiwisolver=1.4.7=py311h2c37856_0
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libarchive=3.7.7=h7c07d2a_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcurl=8.13.0=h73640d1_0
  - libcxx=20.1.3=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libgd=2.3.3=hb2c3a21_11
  - libgfortran=14.2.0=heb5dd2a_105
  - libgfortran5=14.2.0=h2c44a93_105
  - libglib=2.84.0=hdff4504_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.23.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_0
  - libmamba=2.0.3=h4621f14_0
  - libmambapy=2.0.3=py311hf0c8158_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - librsvg=2.58.4=h266df6f_3
  - libsodium=1.0.20=h99b78c6_0
  - libsolv=0.7.30=h6c9b7f8_0
  - libsqlite=3.49.1=h3f77e49_2
  - libssh2=1.11.1=h9cc3647_0
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.7=h52572c6_1
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.3=hdb05f8b_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=h313beb8_1
  - lzo=2.10=h93a5062_1001
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py311h4921393_1
  - matplotlib=3.9.4=py311ha1ab1f8_0
  - matplotlib-base=3.9.4=py311h031da69_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - menuinst=2.2.0=py311h267d04e_0
  - mergedeep=1.3.4=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - nibabel=5.3.2=pyha770c72_1
  - nlohmann_json=3.11.3=h00cdb27_1
  - notebook=7.4.0=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=1.26.4=py311h7125741_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyhd8ed1ab_0
  - pandas=2.2.3=py311hca32420_3
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.3=h5fd7515_1
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h297a79d_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py311hb9ba9e9_0
  - pip=25.0.1=pyh8b19718_0
  - pixman=0.44.2=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - prompt_toolkit=3.0.51=hd8ed1ab_0
  - psutil=7.0.0=py311h917b07b_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h917b07b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-core=2.33.1=py311hc9d6b66_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyobjc-core=11.0=py311hab620ed_0
  - pyobjc-framework-cocoa=11.0=py311hab620ed_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.12=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python.app=1.4=py311hdc19893_4
  - python_abi=3.11=6_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h8b6d4dd_1
  - pyyaml=6.0.2=py311h4921393_2
  - pyzmq=26.4.0=py311h01f2145_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1a28f6b_0
  - referencing=0.36.2=pyh29332c3_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=14.0.0=pyh29332c3_0
  - rpds-py=0.24.0=py311hc9d6b66_0
  - ruamel.yaml=0.18.10=py311h917b07b_0
  - ruamel.yaml.clib=0.2.8=py311hae2e1ce_1
  - scikit-image=0.20.0=py311h4eec4a9_1
  - scipy=1.15.2=py311h0675101_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=78.1.1=pyhff2d567_0
  - simdjson=3.10.1=h48ca7d4_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - spdlog=1.14.1=h6d8af72_1
  - sqlite=3.49.1=hd7222ec_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py311h0f07fe1_0
  - sympy=1.13.3=pyh2585a3b_105
  - sympy_plot_backends=3.4.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh31c8845_0
  - tifffile=2020.6.3=py_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.4.2=py311h917b07b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=pyh29332c3_0
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - uncertainties=3.2.3=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py311h917b07b_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h3422bc3_2
  - yaml-cpp=0.8.0=h313beb8_1
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zstandard=0.23.0=py311h917b07b_1
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/homebrew/Caskroom/miniconda/base
